# Generated by Django 5.1.6 on 2025-02-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_app', '0003_alter_users_reporting_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EMS_app.manager'),
        ),
    ]
